import { Order } from './types/order';

export const ORDERS: Order[] = [
  {
    id: '1',
    item: 'Nail Care Order',
    details: 'Nail polish and art kit order',
    status: 'Pending',
    slug: 'nail-care-order',
    date: '2024-07-01',
    items: [
      {
        id: 1,
        title: 'Nail Polish Set',
        slug: 'nail-polish-set',
        imagesUrl: ['url1'],
        price: 29.99,
        heroImage: require('./images/nail-care-hero.png'),
      },
      {
        id: 2,
        title: 'Nail Art Kit',
        slug: 'nail-art-kit',
        imagesUrl: ['url2'],
        price: 39.99,
        heroImage: require('./images/nail-care-1.png'),
      },
    ],
  },
  {
    id: '2',
    item: 'Makeup Order',
    details: 'Foundation and lipstick order',
    status: 'Completed',
    slug: 'makeup-order',
    date: '2024-07-02',
    items: [
      {
        id: 3,
        title: 'Foundation Makeup',
        slug: 'foundation-makeup',
        imagesUrl: ['url3'],
        price: 49.99,
        heroImage: require('./images/makeup-1.png'),
      },
      {
        id: 4,
        title: 'Lipstick Set',
        slug: 'lipstick-set',
        imagesUrl: ['url4'],
        price: 34.99,
        heroImage: require('./images/makeup-2.png'),
      },
    ],
  },
  {
    id: '3',
    item: 'Fragrance Order',
    details: 'Perfume and cologne order',
    status: 'Shipped',
    slug: 'fragrance-order',
    date: '2024-07-03',
    items: [
      {
        id: 5,
        title: 'Floral Perfume',
        slug: 'floral-perfume',
        imagesUrl: ['url5'],
        price: 89.99,
        heroImage: require('./images/fragrance-1.png'),
      },
      {
        id: 6,
        title: 'Woody Cologne',
        slug: 'woody-cologne',
        imagesUrl: ['url6'],
        price: 79.99,
        heroImage: require('./images/fragrance-2.png'),
      },
    ],
  },
  {
    id: '4',
    item: 'Mixed Order',
    details: 'Mixed category order',
    status: 'InTransit',
    slug: 'mixed-order',
    date: '2024-07-04',
    items: [
      {
        id: 1,
        title: 'Nail Polish Set',
        slug: 'nail-polish-set',
        imagesUrl: ['url7'],
        price: 29.99,
        heroImage: require('./images/nail-care-hero.png'),
      },
      {
        id: 3,
        title: 'Foundation Makeup',
        slug: 'foundation-makeup',
        imagesUrl: ['url8'],
        price: 49.99,
        heroImage: require('./images/makeup-1.png'),
      },
      {
        id: 5,
        title: 'Floral Perfume',
        slug: 'floral-perfume',
        imagesUrl: ['url9'],
        price: 89.99,
        heroImage: require('./images/fragrance-1.png'),
      },
    ],
  },
];